
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[179] =
    {   0,
        0,    0,    0,    0,   72,   70,   29,   30,   55,   70,
       38,   23,    4,    5,   50,   48,    7,   49,   34,   51,
       11,   31,    6,   46,   43,   41,    3,   69,   69,   69,
       69,   69,   69,   69,   69,    9,   37,   10,   39,   70,
       28,   68,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   26,   25,   24,   29,   17,   22,   54,   32,   33,
        2,   35,   14,   13,   11,    0,    8,   47,   45,   42,
       40,   69,   69,   69,   18,   19,   69,   20,   69,   69,
       69,    0,    0,   28,   68,   69,   69,   58,   69,   69,
       69,   69,   69,   69,   66,   69,   36,    0,   13,    0,

        0,   12,   52,   69,   53,   21,   69,   69,    0,   27,
        0,   69,   56,   58,   58,   59,   69,   69,   69,   63,
       69,   69,   66,   66,   69,    0,   14,    0,    0,   13,
       69,   15,   69,   44,   69,   56,   56,   59,   59,   60,
       69,   69,   63,   63,   64,   69,   69,    0,   13,   16,
        1,   57,   60,   60,   69,   69,   64,   64,   65,   67,
       57,   57,   69,   62,   65,   65,   67,   67,   69,   62,
       62,   69,   69,   69,   61,   61,   61,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       35,   41,   42,   43,   44,   45,   46,   35,   35,   35,
        1,    1,    1,    1,   47,    1,   35,   35,   35,   35,

       48,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   49,   50,   51,   52,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   53,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   54,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   55,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[184] =
    {   0,
        0,   54,   52,   54,  622, 1210,  619, 1210, 1210,    0,
     1210, 1210,  556, 1210,  528,  526, 1210,   45,   46, 1210,
       51, 1210, 1210,   50, 1210,   51, 1210,    0,  505,  512,
       30,  507,  495,   50,  477, 1210,  458, 1210, 1210,  454,
      504,    0,  466,   50,   49,  475,  440,   58,  448,   64,
       60, 1210, 1210, 1210,  474, 1210, 1210, 1210, 1210, 1210,
     1210,  459,   78,   80,   86,   93, 1210, 1210, 1210, 1210,
     1210,    0,  429,  437,    0,    0,  382,    0,  338,  293,
      307,  332,  280,  331,    0,  288,  248,  134,  231,  237,
      229,  237,  240,   85,  189,  236, 1210,   99,  227,  103,

      250,  249,    0,  224,    0,    0,  236,  223,  260, 1210,
      240,  223,  275,  313,    0,  361,  220,  230,  229,  416,
      229,  226,  454,    0,  211,  235,  234,  233,  232,  231,
      218,    0,  163, 1210,   94,  485,    0,  516,    0,  564,
       92,  105,  602,    0,  650,   88,  101,  111,  107,    0,
        0,  705,  743,    0,   99,   80,  774,    0,  822,  877,
      915,    0,   93,  963, 1001,    0, 1032,    0,   76, 1063,
        0,   80,   49,   61, 1111, 1149,    0, 1210, 1197, 1200,
       74, 1203, 1206
    } ;

static yyconst flex_int16_t yy_def[184] =
    {   0,
      178,    1,  179,  179,  178,  178,  178,  178,  178,  180,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  181,  181,  181,
      181,  181,  181,  181,  181,  178,  178,  178,  178,  178,
      178,  182,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  183,  178,  178,  182,  181,  181,  178,  181,  181,
      181,  181,  181,  181,  178,  181,  178,  178,  178,  178,

      178,  178,  181,  181,  181,  181,  181,  181,  183,  178,
      178,  181,  178,   88,   88,  178,  181,  181,  181,  178,
      181,  181,   95,   95,  181,  178,  178,  178,  178,  178,
      181,  181,  181,  178,  181,  113,  113,  116,  116,  178,
      181,  181,  120,  120,  178,  181,  181,  178,  178,  181,
      181,  178,  140,  140,  181,  181,  145,  145,  178,  178,
      152,  152,  181,  178,  159,  159,  160,  160,  181,  164,
      164,  181,  181,  181,  178,  175,  175,    0,  178,  178,
      178,  178,  178
    } ;

static yyconst flex_int16_t yy_nxt[1266] =
    {   0,
        6,    7,    8,    6,    6,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   29,   28,   30,
       28,   28,   28,   28,   28,   28,   28,   31,   28,   28,
       32,   33,   34,   28,   28,   35,    6,   28,   36,   37,
       38,   39,    6,    6,   40,   41,   53,   42,   53,   60,
       54,   62,   54,   63,   67,   75,   64,   61,   65,   76,
       68,   69,   70,   71,   79,   88,   72,   89,   87,   66,
       43,   44,   73,   92,   45,   46,   47,   93,   79,  175,
       80,   81,   48,  174,   49,   63,   50,   99,   66,   51,

       96,   64,   95,   65,   80,  101,   98,  101,  100,  121,
      102,  126,  173,  126,   66,  129,  127,  129,  172,  169,
      130,  105,  164,  163,  149,   98,  122,  100,  149,  160,
      159,  156,  155,   66,  114,  114,  152,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  115,  114,  114,  114,  114,  114,  114,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  114,  114,  114,  114,  114,  114,  114,  123,
      123,  151,  123,  123,  123,  123,  123,  123,  123,  123,

      123,  123,  123,  123,  123,  123,  124,  123,  123,  123,
      123,  123,  123,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  123,  123,  123,
      123,  123,  123,  123,   99,  148,  150,  148,  130,  130,
      149,  127,  127,  147,  146,  128,  145,  142,  141,  140,
      135,  134,  110,  133,  132,  131,  102,  102,  125,  120,
      119,  118,  117,  116,  128,  136,  136,  113,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  137,  136,  136,  136,  136,  136,  136,  137,

      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  136,  136,  136,  136,  136,  136,  136,
      114,  112,   84,  111,  110,  108,  107,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  138,  138,  106,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  139,  138,
      138,  138,  138,  138,  138,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,

      139,  139,  139,  139,  139,  139,  139,  139,  139,  138,
      138,  138,  138,  138,  138,  138,  143,  143,  105,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  144,  143,  143,  143,  143,  143,  143,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  143,  143,  143,  143,  143,  143,
      143,  123,  104,  103,   97,   55,   94,   91,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,

      123,  123,  136,   90,   86,   84,   83,   82,   81,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  138,   78,   77,   74,   73,   59,   58,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  153,  153,   57,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  154,  153,  153,  153,  153,  153,  153,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,

      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  153,  153,  153,  153,  153,  153,  153,  143,
       55,  178,  178,  178,  178,  178,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      157,  157,  178,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  158,  157,  157,
      157,  157,  157,  157,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  157,  157,

      157,  157,  157,  157,  157,  161,  161,  178,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  162,  161,  161,  161,  161,  161,  161,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  161,  161,  161,  161,  161,  161,  161,
      153,  178,  178,  178,  178,  178,  178,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  157,  178,  178,  178,  178,  178,  178,  157,  157,

      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  165,  165,  178,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  166,
      165,  165,  165,  165,  165,  165,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      165,  165,  165,  165,  165,  165,  165,  167,  167,  178,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  168,  167,  167,  167,  167,  167,

      167,  168,  168,  168,  168,  168,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  167,  167,  167,  167,  167,
      167,  167,  161,  178,  178,  178,  178,  178,  178,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  170,  170,  178,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      171,  170,  170,  170,  170,  170,  170,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,

      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  170,  170,  170,  170,  170,  170,  170,  165,  178,
      178,  178,  178,  178,  178,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  167,
      178,  178,  178,  178,  178,  178,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      170,  178,  178,  178,  178,  178,  178,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,

      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  176,  176,  178,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  177,  176,
      176,  176,  176,  176,  176,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  176,
      176,  176,  176,  176,  176,  176,  176,  178,  178,  178,
      178,  178,  178,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,   52,   52,   52,

       56,  178,   56,   85,  178,   85,  109,  109,  109,    5,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178
    } ;

static yyconst flex_int16_t yy_chk[1266] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    3,    2,    4,   18,
        3,   19,    4,   19,   24,   31,   21,   18,   21,   31,
       24,   24,   26,   26,   34,   45,  181,   45,   44,   21,
        2,    2,   44,   48,    2,    2,    2,   48,   50,  174,
       34,   51,    2,  173,    2,   63,    2,   64,   21,    2,

       51,   65,   50,   65,   50,   66,   63,   66,   64,   94,
       66,   98,  172,   98,   65,  100,   98,  100,  169,  163,
      100,   94,  156,  155,  149,   63,   94,   64,  148,  147,
      146,  142,  141,   65,   88,   88,  135,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   95,
       95,  133,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   99,  128,  131,  128,  130,  129,
      128,  127,  126,  125,  122,   99,  121,  119,  118,  117,
      112,  111,  109,  108,  107,  104,  102,  101,   96,   93,
       92,   91,   90,   89,   99,  113,  113,   87,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,

      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      114,   86,   84,   83,   82,   81,   80,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  116,  116,   79,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,

      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  120,  120,   77,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  123,   74,   73,   62,   55,   49,   47,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,

      123,  123,  136,   46,   43,   41,   40,   37,   35,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  138,   33,   32,   30,   29,   16,   15,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  140,  140,   13,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,

      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  143,
        7,    5,    0,    0,    0,    0,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      145,  145,    0,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,

      145,  145,  145,  145,  145,  152,  152,    0,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      153,    0,    0,    0,    0,    0,    0,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  157,    0,    0,    0,    0,    0,    0,  157,  157,

      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  159,  159,    0,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  160,  160,    0,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,

      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  161,    0,    0,    0,    0,    0,    0,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  164,  164,    0,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  165,    0,
        0,    0,    0,    0,    0,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  167,
        0,    0,    0,    0,    0,    0,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      170,    0,    0,    0,    0,    0,    0,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,

      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  175,  175,    0,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  176,    0,    0,    0,
        0,    0,    0,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  179,  179,  179,

      180,    0,  180,  182,    0,  182,  183,  183,  183,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
/* scanner for sasl */
#line 4 "lex.l"
#include <math.h>	/* need this for the call to atof() below */
#include <string.h>	/* need this for strchr() */
#include "lex.h"	/* token definitions etc */
static tok lex_token;
static int lex_got_token = 0;	/* is lex_token ready and unconsumed? */
int lex_col = 0;	/* current column (fixed width character set ;-), source program columns are numbered 1..  */
int lex_margin = 0;	/* offside column, token is offside when (col <= margin), initially 0 */
int lex_got_newline = 0;	/* 1 iff current token is preceded by newline (since previous token) */
static int margins[1000] = {0};
static int m = 0;	 /* margins[m] is current offside setting */
tok_const lex_tc;	/* indicator set when tok_constant found - indicates which constant is found */
tok_op lex_oper;       	/* indicator set when tok_operator found - which operator */
char lex_oper_prio;	/* indicator set when tok_operator found - operator priority */
char *lex_oper_fix;	/* indicator set when tok_operator found - "i"=infix, "p"=prefix, "o"=postfix also "ip" if can be prefix *or* infix */
char lex_oper_assoc;	/* indicator set when tok_operator found - 'r' right associative, 'l' left acssociative, 'n'=non-associative, '? ???*/
void lex_offside() /* set current column as limit of offside */
{
m++; /* assert(m<max) */
margins[m] = lex_margin = lex_col;
if (debug>1)
fprintf(stderr,"offside:%d\n", lex_margin);
}
static void scan();
void lex_onside()
{
m--; /* assert(m>=0) */
lex_margin = margins[m];
if (debug>1)
fprintf(stderr,"onside:%d\n", lex_margin);
scan();/* is a token revelealed by the new margin? */
}
/* if token is offsideable and is offside, return tok_offside; otherwise return the token updating lex_col */
/* off!==0 => offsideable */
/* add width of current token to lex_col, allowing for tabs */
static void grow()
{
char *s;
for (s = yytext; *s; s++) {
if (*s == '\n')
lex_col = 0;
if (*s == '\t')
lex_col = ((lex_col / 8) + 1) * 8;
else
lex_col++;
}
}
/* grow lex_col for current match and return the token */
static tok indent(tok t)
{
grow();
return t;
}
static tok off(tok t);

int lex_nesting = 0;
#line 844 "<stdout>"

#define INITIAL 0
#define STRING 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 78 "lex.l"


	/* delimiters */

#line 1035 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 179 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1210 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 82 "lex.l"
{ LEX_DEBUG("A Where: %s\n", yytext); return off(tok_where); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 83 "lex.l"
{ LEX_DEBUG("A then: %s\n", yytext); return off(tok_then); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 85 "lex.l"
{ LEX_DEBUG("A question mark: %s\n", yytext); return indent(tok_question_mark); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 87 "lex.l"
{ LEX_DEBUG("A left paren: %s\n", yytext); return off(tok_left_paren); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 88 "lex.l"
{ LEX_DEBUG("A right paren: %s\n", yytext); return off(tok_right_paren); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "lex.l"
{ LEX_DEBUG("A semi-colon: %s\n", yytext); return off(tok_semicolon); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 90 "lex.l"
{ LEX_DEBUG("A comma: %s\n", yytext); return off(tok_comma); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "lex.l"
{ LEX_DEBUG("A generator: %s\n", yytext); return off(tok_generator); /* ZF */ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "lex.l"
{ LEX_DEBUG("A left paren: %s\n", yytext);  return off(tok_left_brace); /* ZF */}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "lex.l"
{ LEX_DEBUG("A right paren: %s\n", yytext); return off(tok_right_brace); /* ZF */ }
	YY_BREAK
/* Constants - all tok_constant, with associated tok_const_xxx subtype */
/* numbers */
case 11:
YY_RULE_SETUP
#line 99 "lex.l"
{ LEX_DEBUG2( "An integer: %s (%d)\n", yytext, atoi( yytext ) ); lex_tc = tok_const_integer; return off(tok_constant); /* prefer to make integers; TODO make float iff integer has too many digts */ }
	YY_BREAK
/* floating point numbers
	atof() format definition:
		"decimal floating point expression. It consists of the following parts:
		1.(optional) plus or minus sign
		2.nonempty sequence of decimal digits optionally containing decimal point character (as determined by the current C locale) (defines significand)
		3.(optional) e or E followed with optional minus or plus sign and nonempty sequence of decimal digits (defines exponent)"

	need three cases to cover "non-empty sequenc of decimal digits optionally including decimal point", the rest is simple
	note leading SIGN +/- is dealt with as unary operator below
	*/     
case 12:
#line 112 "lex.l"
case 13:
#line 113 "lex.l"
case 14:
YY_RULE_SETUP
#line 113 "lex.l"
{ LEX_DEBUG2( "A float: %s (%g)\n", yytext, atof(yytext)); lex_tc = tok_const_floating; return off(tok_constant); }
	YY_BREAK
/* truth values */
case 15:
YY_RULE_SETUP
#line 117 "lex.l"
{ LEX_DEBUG("A boolconst: %s\n", yytext); lex_tc = tok_const_true; return off(tok_constant); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "lex.l"
{ LEX_DEBUG("A boolconst: %s\n", yytext); lex_tc = tok_const_false; return off(tok_constant); }
	YY_BREAK
/* characters */
case 17:
YY_RULE_SETUP
#line 121 "lex.l"
{ LEX_DEBUG("A charconst: %s\n", yytext+1); lex_tc = tok_const_char; return off(tok_constant); /* the character is in yytext[1] */ }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 122 "lex.l"
{ LEX_DEBUG("A special char: %s\n", yytext); lex_tc = tok_const_special_char_NL; return off(tok_constant); /* the special char is in yytext[0]*/ }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 123 "lex.l"
{ LEX_DEBUG("A special char: %s\n", yytext); lex_tc = tok_const_special_char_NP; return off(tok_constant); /* the special char is in yytext[0]*/ }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 124 "lex.l"
{ LEX_DEBUG("A special char: %s\n", yytext); lex_tc = tok_const_special_char_SP; return off(tok_constant); /* the special char is in yytext[0]*/ }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 125 "lex.l"
{ LEX_DEBUG("A special char: %s\n", yytext); lex_tc = tok_const_special_char_TAB; return off(tok_constant); /* the special char is in yytext[0]*/ }
	YY_BREAK
/* nil */
case 22:
YY_RULE_SETUP
#line 128 "lex.l"
{ LEX_DEBUG("A nil: %s\n", yytext); lex_tc = tok_const_nil; return off(tok_constant); }
	YY_BREAK
/* end of Constants */
/* string */
case 23:
YY_RULE_SETUP
#line 134 "lex.l"
{ BEGIN(STRING); LEX_DEBUG("Start string: %s\n", yytext); lex_nesting = 1; lex_tc = tok_const_string_start; return off(tok_constant); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 135 "lex.l"
{ LEX_DEBUG("Start nested string: %s\n", yytext); lex_nesting++; lex_tc = tok_const_string_start_nested; return indent(tok_constant); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 136 "lex.l"
{
  			if (--lex_nesting <= 0) 
			{
				BEGIN(INITIAL);	/* reset prefix */	
 				LEX_DEBUG("String end: %s\n", yytext);
				lex_tc = tok_const_string_end;
			}
			else
			{
    				LEX_DEBUG("String nested end: %s\n", yytext);
				lex_tc = tok_const_string_end_nested;
			}
			return indent(tok_constant);
		}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 150 "lex.l"
{ LEX_DEBUG("String item: %s\n", yytext); lex_tc = tok_const_string_char; return indent(tok_constant); /* allow string to contain newlines */ }
	YY_BREAK
/* End Constants */
/* comments */
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 156 "lex.l"
{ LEX_DEBUG("A Comment: %s", yytext); yyless(yyleng - 1); grow(); /* put back the newline terminator - consume without returning */}
	YY_BREAK
/* whitespace */
case 28:
YY_RULE_SETUP
#line 159 "lex.l"
{ grow();  /* leading whitespace - calculate indentation level - consume without returning */ }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 161 "lex.l"
{ LEX_DEBUG2("Whitespace \"%s\" (%lu characters)\n", yytext, strlen(yytext)); grow();  /* no need to return a token */ }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 163 "lex.l"
{ LEX_DEBUG0("A Newline.\n"); lex_got_newline = 1; grow();  /* no need to return a token */ }
	YY_BREAK
/* Operators - in order from 1 of increasing binding power */
case 31:
YY_RULE_SETUP
#line 166 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'r'; lex_oper = op_colon; return off(tok_operator); /* <<-- lhs/rhs symbol overload to be sorted in parser */ }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 167 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'r'; lex_oper = op_plusplus; return off(tok_operator); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 168 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'r'; lex_oper = op_minusminus; return off(tok_operator); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 170 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'r'; lex_oper = op_period; return off(tok_operator);
	  /* period - [Turner 1983]: not in the language definition, but *is* in the prelude */
	  /* we choose to make is the most binding infix operator, binding to the right */
	  /* "f.g.h x" is interpreted as f.g.(h x) and in turn as "f (g (h x))" */
	}     
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 176 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'n'; lex_oper = op_range; return off(tok_operator); }	/* ZF */
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 178 "lex.l"
{ lex_oper_fix = "o"; lex_oper_assoc = '?'; lex_oper = op_range_unbounded; return off(tok_operator); }	/* ZF */
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 180 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_or; return off(tok_operator); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 182 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_and; return off(tok_operator); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 184 "lex.l"
{ lex_oper_fix = "p"; lex_oper_assoc = '?'; lex_oper = op_unary_not; return off(tok_operator); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 186 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_much_greater; return off(tok_operator); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 187 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_greater; return off(tok_operator); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 188 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_greater_equal; return off(tok_operator); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 189 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_equal; return off(tok_operator); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 190 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_not_equal; return off(tok_operator); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 191 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_less_equal; return off(tok_operator); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 192 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_less; return off(tok_operator); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 193 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_much_less; return off(tok_operator); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 195 "lex.l"
{ lex_oper_fix = "ip"; lex_oper_assoc = 'l'; lex_oper = op_plus; return off(tok_operator); } /* <<-- prefix/infix TODO different assoc if necessary */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 196 "lex.l"
{ lex_oper_fix = "ip"; lex_oper_assoc = 'l'; lex_oper = op_minus; return off(tok_operator); } /* <<-- prefix/infix TODO different assoc if necessary */
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 198 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_times; return off(tok_operator); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 199 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_divide; return off(tok_operator); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 200 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_int_divide; return off(tok_operator); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 201 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'l'; lex_oper = op_rem; return off(tok_operator); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 203 "lex.l"
{ lex_oper_fix = "i"; lex_oper_assoc = 'r'; lex_oper = op_power; return off(tok_operator); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 205 "lex.l"
{ lex_oper_fix = "p"; lex_oper_assoc = '?'; lex_oper = op_unary_count; return off(tok_operator); }	/* ZF */
	YY_BREAK
/* directives - for interactive use, not part of the sasl languages itself */
case 56:
YY_RULE_SETUP
#line 210 "lex.l"
{ LEX_DEBUG( "DEF: %s\n", yytext); return indent(tok_def); }
	YY_BREAK
case 57:
#line 213 "lex.l"
case 58:
#line 214 "lex.l"
case 59:
#line 215 "lex.l"
case 60:
#line 216 "lex.l"
case 61:
#line 217 "lex.l"
case 62:
#line 218 "lex.l"
case 63:
#line 219 "lex.l"
case 64:
#line 220 "lex.l"
case 65:
#line 221 "lex.l"
case 66:
#line 222 "lex.l"
case 67:
YY_RULE_SETUP
#line 222 "lex.l"
{ LEX_DEBUG( "A command: %s\n", yytext); return indent(tok_command); 	/* "interactive" user commands - yytext includes remainder of line to be analysed */ }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 223 "lex.l"
{ LEX_DEBUG( "A shell command: %s\n", yytext+1); return indent(tok_command); /* shell escape - yytext includes remainder of line to be executed */ }
	YY_BREAK
/* names */     
case 69:
YY_RULE_SETUP
#line 227 "lex.l"
{ LEX_DEBUG( "A name: %s\n", yytext ); return off(tok_name); }
	YY_BREAK
/* Unrecognised */
case 70:
YY_RULE_SETUP
#line 231 "lex.l"
{ LEX_DEBUG2( "Unrecognized character: %s (%u)\n", yytext, (unsigned) yytext[0] ); grow(); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 233 "lex.l"
ECHO;
	YY_BREAK
#line 1482 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 179 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 179 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 178);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 233 "lex.l"


     

int yywrap() { return(1);}	/* Return True - yes exit when first EOF encountered */

/* 
 * lexer - lex...
 * flex(1) does such a beautiful job we don't need much here
 */

/*
 * lex_get_prio(oper, fix) - return the priority for given operator, 
 * if oper has more than one prio then use assoc to dsiambiguate
 * Used to set extern lex_oper_prio
 */
static int lex_get_prio(tok_op op, char fix)
{
  switch(op) {
  case op_colon: return 1;
  case op_plusplus: return 1;
  case op_minusminus: return 1;

  case op_range: return 2;

  case op_range_unbounded: return 3;

  case op_or: return 4;

  case op_and: return 5;

  case op_unary_not: return 6;

  case op_much_greater: return 7;
  case op_greater: return 7;
  case op_greater_equal: return 7;
  case op_equal: return 7;
  case op_not_equal: return 7;
  case op_less_equal: return 7;
  case op_less: return 7;
  case op_much_less: return 7;

  case op_plus: return (fix == 'i' ? 8 : 9);
  case op_minus: return (fix == 'i' ? 8 : 9);

  case op_times: return 10;
  case op_divide: return 10;
  case op_int_divide: return 10;
  case op_rem: return 10;

  case op_power: return 11;

  case op_period: return 12;

  case op_unary_count: return 13;

  /*no 'default:' - compiler then checks all cases are covered */

  }
  /*NOTREACHED*/
}

int lex_depth = 0; /* how many characters before the current token eg 0 when no indent, 8 when one tab indent */
int lex_new_depth =0;	/* "lex_depth = yyleng" = how many characters to end of current token */

/*
 * lex_looking_at - conditionally get token.
 * returns 1 and consumes token iff the lookahead token is t
 * otherwise 0 is returned and the lookahead token is unchanged
 *
 * NB lex_looking_at() can be called multiple times between calls to yylex()
 */

static void scan()
{
  /* ensure lookahead token is set - may be initial token, or following offside */
  if (!lex_got_token || lex_token == tok_offside) {
    lex_token = yylex();
    lex_got_token = 1;
  }
  else if (lex_token == tok_offside)
    LEX_DEBUG0("scan: got token but it's tok_offside\n");/* error */
}

/* check if token is offside, return tok_offside, otherwise indent and return the token */
static tok off(tok t)
{
  if (lex_col < lex_margin) {
    LEX_DEBUG("It's offside: %s\n", yytext);
    yyless(0);	/* put the token back for reprocessing when margin changes */
    return tok_offside;
  }
  grow();
  return t;
}

/*
 * consume() - use the current token (and its preceeding newline)
 */
static void consume()
{
      lex_got_newline = 0;
      lex_got_token = 0;
}

/* match current token and consume it */
int lex_looking_at(tok t)
{
  /* ensure lookahead token is set */
  scan();

  /* if match then consume lookahead token */
  if (lex_token == t) {
    consume();
    return 1;
    }
  return 0;
}

#ifdef nolonger
/* examine token without consuming it */
/* NB when parsing need to use this, as lex_got_token may be 0 */
int lex_peeking_at(tok t)
{
  scan();
  return lex_token == t;
}
#endif

int lex_peeking_at_simple()
{
  scan();
  return (lex_token == tok_name) ||
    (lex_token == tok_constant) ||
    (lex_token == tok_left_paren);
}

/* match either current token, or else a newline since previous token, followed by <simple> */

/* looking_at(tok_semicolon) || (got_newline && peeking_at(<simple>)) */
/* if looking_at(tok_semicolon) must have another clause
 * if newline then clause is optional - if the next token is onside then clause else not 
 */
int lex_looking_at_or_onside_newline(tok t)
{
  if (lex_looking_at(t))
    return 1;

  if (lex_got_newline && lex_peeking_at_simple()) {
    lex_got_newline = 0;
    return 1;
  }

  return 0;
}

/* match a token; if "no_newline" then only match when no newline has been seen since previus token */
int lex_looking_at_no_newline(tok t, char no_newline)
{
  /* ensure token is set */
  scan();

  if (no_newline && lex_got_newline)
    return 0; /* do not consume token or newline */

  if (lex_token == t) {
    consume();
    return 1;
  }
  return 0;
}

/*
 * special case to match specific operator tokens */
int lex_looking_at_operator(tok_op op)
{
  /* ensure token is set */
  scan();

  /* if match then consume lookahead token */
  if (lex_token == tok_operator && lex_oper == op) {
    consume();
    return 1;
  }
  return 0;  
}

/* 
 * special case to identify operator classes, and of priority>=p (more binding or same)
 * return operator priority (>0) of matched operators, otherwise 0
 */
static char the_fix[] = " ";

int lex_looking_at_operator_fix_prio(char fix, char prio)
{
  /* ensure lookahead token is set */
  scan();

  /* if match then consume lookahead token, and set priority - which depending on 'fix' */
  if (lex_token == tok_operator && (strchr(lex_oper_fix, fix) != NULL)) {
    /* got a operator with matching fix */
    the_fix[0] = fix; lex_oper_fix = the_fix; /* make this "sticky" - set the lex_oper_fix even if prio is wrong */
    lex_oper_prio = lex_get_prio(lex_oper, fix);
    LEX_DEBUG2("An operator: prio %d fix \"%s\"\n", lex_oper_prio, lex_oper_fix);
    /* check priority */
    if (lex_oper_prio >= prio) { 
      consume();
      return lex_oper_prio;
    }
  }
  return 0;
}

